version: "3.8"

services:
    db:
        image: mysql:8.0
        container_name: xyzstay-db
        restart: always
        environment:
            MYSQL_DATABASE: xyzstay
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: xyzstay
            MYSQL_PASSWORD: xyzstay
        ports:
            - "3307:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 5s
            timeout: 5s
            retries: 10
            start_period: 10s

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: xyzstay-phpmyadmin
        restart: always
        ports:
            - "8080:80" # access via http://localhost:8080
        environment:
            PMA_HOST: db # points to your MySQL service
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: root
        depends_on:
            - db
        networks:
            - laravel

    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: xyzstay-backend
        volumes:
            - ./:/var/www
        networks:
            - laravel
        depends_on:
            db:
                condition: service_healthy
        environment:
            DB_CONNECTION: mysql
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: xyzstay
            DB_USERNAME: xyzstay
            DB_PASSWORD: xyzstay
        entrypoint: ["/usr/local/bin/entrypoint.sh"]
        ports:
            - "9000:9000"

    webserver:
        image: nginx:alpine
        container_name: xyzstay-nginx
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

networks:
    laravel:
        external: true

volumes:
    dbdata:
